spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://huangxuwei.com:3306/huangxuwei?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: huangxuwei
    password: HKLC6c4zY7xMheNd


mybatis:
  type-aliases-package: com.wei.entity
  mapper-locations: mapper/*.xml